version: '3.8'

services:
  ollama:
    build: .
    container_name: ollama-server
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11433:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.chatbot
    container_name: chatbot-api
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - SECRET_KEY=FLAG{pr0mpt_1nj3ct10n_vuln3r4bl3_by_derry}
    restart: unless-stopped

volumes:
  ollama_data:
